# Generated by Django 3.1 on 2020-09-10 19:38

import design.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Раздел')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('excerpt', models.TextField(blank=True, db_index=True, null=True, verbose_name='Описание статьи')),
                ('year', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2008), design.models.max_value_current_year], verbose_name='Год реализации')),
                ('cover', models.ImageField(upload_to='portfolio/', verbose_name='Главное фото')),
                ('status', models.CharField(choices=[('0', 'Реализован'), ('1', 'В стадии реализации')], default='0', max_length=1, verbose_name='Статус')),
                ('category', models.ManyToManyField(blank=True, to='design.Category')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('file', models.ImageField(default='/no-image.png', storage=design.models.MediaFileStorage(), upload_to='portfolio/', verbose_name='Фото')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя файла')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='design.project')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
