"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os, sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Добавим общую папку для хранения приложений
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'z$m#y!+kchxv)ho1y2&lvlgf-hyp$t9fii336kv5a04o5r=spm'
SECRET_KEY = os.environ.get('SECRET_KEY', 'z$m#y!+kchxv)ho1y2&lvlgf-hyp$t9fii336kv5a04o5r=spm')
print(SECRET_KEY)
# only for production
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'z$m#y!+kchxv)ho1y2&lvlgf-hyp$t9fii336kv5a04o5r=spm')
# SECRET_KEY = '#7rmni#sjhr^t$u56*x4=wfr+nutf1($1xjv($2w=m#68%e$4w' # <--- annaisupova.com production key

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# Alternative method to switch debug off for production
DEBUG = bool( os.environ.get('DEBUG', True) )
print(DEBUG)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorl.thumbnail',
    #'crispy_forms',
    'design',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # Production
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'a0467449_a-studia',
    #     'USER': 'a0467449_a-studia',
    #     'PASSWORD': 'AnyaIsupova',
    #     'HOST': 'localhost',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler"
 ]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "artservice08@yandex.ru"
# EMAIL_HOST_PASSWORD = "xdbhoybbgqugmbwk"
# EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = "annaisupova@list.ru"
EMAIL_HOST_PASSWORD = "A-studia_support"
EMAIL_USE_SSL = True

EMAIL_RICIPIENTS = ['saloon.as@gmail.com']
SERVER_EMAIL = EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# sorl-thumbnail settings
THUMBNAIL_ALIASES = {
    '': {
        'logo': {'size': (100,150), 'crop': False},
        'post_thumb': {'size': (280,280), 'crop': True},
    },
}
THUMBNAIL_QUALITY = 85
THUMBNAIL_UPSCALE = False
THUMBNAIL_FILTER_WIDTH = 600
#Resolution multiplicators, e.g. value 2 means for every thumbnail of regular size x*y, additional thumbnail of 2x*2y size is created.
THUMBNAIL_ALTERNATIVE_RESOLUTIONS = [2,2]
#THUMBNAIL_PROGRESSIVE = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# for production
# STATIC_ROOT = os.path.join(BASE_DIR, 'public_html/static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Base url to serve media files
MEDIA_URL = '/media/'

# Path where media is stored
# for production
# MEDIA_ROOT = os.path.join(BASE_DIR, 'public_html/media')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
